/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stepmotormusic;

import java.awt.FileDialog;
import java.io.File;
import java.util.List;

/**
 *
 * @author Simon Spies
 */
public class Main extends javax.swing.JFrame {

    String file = null;
    Thread play = null;
    
    /**
     * Creates new form Main
     */
    public Main() {
        try {
        initComponents();
        
        List<String> availablePorts = StepmotorMusic.getSerialPorts();
        
        if (!availablePorts.isEmpty()) {
            selectPortList.removeAllItems();
            
            for (String port : availablePorts)
                selectPortList.addItem(port);
        }
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        selectFileButton = new javax.swing.JButton();
        selectPortList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stepmotororgan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("File:");

        fileLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fileLabel.setText("No file selected!");
        fileLabel.setName("fileNameLabel"); // NOI18N

        playButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        playButton.setText("Play");
        playButton.setName("playButton"); // NOI18N
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(188);
        jSplitPane1.setEnabled(false);

        selectFileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectFileButton.setText("Select File");
        selectFileButton.setMaximumSize(new java.awt.Dimension(188, 31));
        selectFileButton.setMinimumSize(new java.awt.Dimension(188, 31));
        selectFileButton.setName("selectFileButton"); // NOI18N
        selectFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectFileButtonMouseClicked(evt);
            }
        });
        jSplitPane1.setLeftComponent(selectFileButton);

        selectPortList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectPortList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Port Selected" }));
        selectPortList.setMinimumSize(new java.awt.Dimension(188, 28));
        jSplitPane1.setRightComponent(selectPortList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSplitPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fileLabel))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileButtonMouseClicked
        FileDialog fd = new FileDialog(this, "Choose a midi file", FileDialog.LOAD);
        fd.setDirectory("C:\\");
        fd.setFile("*");
        fd.setMultipleMode(false);
        fd.setVisible(true);
        File[] files = fd.getFiles();
        
        if (files.length == 0)
            return;
        
        file = files[0].getAbsolutePath();
        fileLabel.setText(files[0].getName());
    }//GEN-LAST:event_selectFileButtonMouseClicked

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        if (play != null && play.isAlive() && !play.isInterrupted()) {
            play.interrupt();
            playButton.setText("Play");
            selectFileButton.setEnabled(true);
            selectPortList.setEnabled(true);
        } else if (file != null && !selectPortList.getSelectedItem().toString().equals("No Port Selected")) {
            play = new Thread(new StepmotorMusic(this, file, selectPortList.getSelectedItem().toString()));
            play.start();
            playButton.setText("Stop");
            selectFileButton.setEnabled(false);
            selectPortList.setEnabled(false);
        }
    }//GEN-LAST:event_playButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void playThreadInterrupted() {
        playButton.setText("Play");
        selectFileButton.setEnabled(true);
        selectPortList.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JComboBox<String> selectPortList;
    // End of variables declaration//GEN-END:variables
}
